/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as ApiTtsRouteImport } from './routes/api/tts'
import { Route as AppAgentsIndexRouteImport } from './routes/_app.agents.index'
import { Route as AppAgentsAgentIdRouteImport } from './routes/_app.agents.$agentId'
import { Route as AppAgentsTrainingRouteImport } from './routes/_app.agents.training'
import { Route as AppAnalyticsIndexRouteImport } from './routes/_app.analytics.index'
import { Route as AppAppointmentsIndexRouteImport } from './routes/_app.appointments.index'
import { Route as AppCampaignsIndexRouteImport } from './routes/_app.campaigns.index'
import { Route as AppCampaignsIdRouteImport } from './routes/_app.campaigns.$id'
import { Route as AppCampaignsNewRouteImport } from './routes/_app.campaigns.new'
import { Route as AppCustomersIndexRouteImport } from './routes/_app.customers.index'
import { Route as AppCustomersIdRouteImport } from './routes/_app.customers.$id'
import { Route as AppIntegrationsIndexRouteImport } from './routes/_app.integrations.index'
import { Route as AppJourneyIndexRouteImport } from './routes/_app.journey.index'
import { Route as AppSegmentsIndexRouteImport } from './routes/_app.segments.index'
import { Route as AppSegmentsSlugRouteImport } from './routes/_app.segments.$slug'
import { Route as AppSettingsIndexRouteImport } from './routes/_app.settings.index'
import { Route as AppUsersIndexRouteImport } from './routes/_app.users.index'
import { Route as AppVoiceIndexRouteImport } from './routes/_app.voice.index'
import { Route as AppVoiceCallIdRouteImport } from './routes/_app.voice.$callId'
import { Route as AppWhatsappIndexRouteImport } from './routes/_app.whatsapp.index'
import { Route as AppAgentsRecordingsIndexRouteImport } from './routes/_app.agents.recordings.index'
import { Route as AppAgentsRecordingsReviewRouteImport } from './routes/_app.agents.recordings.review'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const ApiTtsRoute = ApiTtsRouteImport.update({
  id: '/api/tts',
  path: '/api/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAgentsIndexRoute = AppAgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentsAgentIdRoute = AppAgentsAgentIdRouteImport.update({
  id: '/agents/$agentId',
  path: '/agents/$agentId',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentsTrainingRoute = AppAgentsTrainingRouteImport.update({
  id: '/agents/training',
  path: '/agents/training',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsIndexRoute = AppAnalyticsIndexRouteImport.update({
  id: '/analytics/',
  path: '/analytics/',
  getParentRoute: () => AppRoute,
} as any)
const AppAppointmentsIndexRoute = AppAppointmentsIndexRouteImport.update({
  id: '/appointments/',
  path: '/appointments/',
  getParentRoute: () => AppRoute,
} as any)
const AppCampaignsIndexRoute = AppCampaignsIndexRouteImport.update({
  id: '/campaigns/',
  path: '/campaigns/',
  getParentRoute: () => AppRoute,
} as any)
const AppCampaignsIdRoute = AppCampaignsIdRouteImport.update({
  id: '/campaigns/$id',
  path: '/campaigns/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppCampaignsNewRoute = AppCampaignsNewRouteImport.update({
  id: '/campaigns/new',
  path: '/campaigns/new',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersIndexRoute = AppCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersIdRoute = AppCustomersIdRouteImport.update({
  id: '/customers/$id',
  path: '/customers/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppIntegrationsIndexRoute = AppIntegrationsIndexRouteImport.update({
  id: '/integrations/',
  path: '/integrations/',
  getParentRoute: () => AppRoute,
} as any)
const AppJourneyIndexRoute = AppJourneyIndexRouteImport.update({
  id: '/journey/',
  path: '/journey/',
  getParentRoute: () => AppRoute,
} as any)
const AppSegmentsIndexRoute = AppSegmentsIndexRouteImport.update({
  id: '/segments/',
  path: '/segments/',
  getParentRoute: () => AppRoute,
} as any)
const AppSegmentsSlugRoute = AppSegmentsSlugRouteImport.update({
  id: '/segments/$slug',
  path: '/segments/$slug',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersIndexRoute = AppUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AppRoute,
} as any)
const AppVoiceIndexRoute = AppVoiceIndexRouteImport.update({
  id: '/voice/',
  path: '/voice/',
  getParentRoute: () => AppRoute,
} as any)
const AppVoiceCallIdRoute = AppVoiceCallIdRouteImport.update({
  id: '/voice/$callId',
  path: '/voice/$callId',
  getParentRoute: () => AppRoute,
} as any)
const AppWhatsappIndexRoute = AppWhatsappIndexRouteImport.update({
  id: '/whatsapp/',
  path: '/whatsapp/',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentsRecordingsIndexRoute =
  AppAgentsRecordingsIndexRouteImport.update({
    id: '/agents/recordings/',
    path: '/agents/recordings/',
    getParentRoute: () => AppRoute,
  } as any)
const AppAgentsRecordingsReviewRoute =
  AppAgentsRecordingsReviewRouteImport.update({
    id: '/agents/recordings/review',
    path: '/agents/recordings/review',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/api/tts': typeof ApiTtsRoute
  '/agents/$agentId': typeof AppAgentsAgentIdRoute
  '/agents/training': typeof AppAgentsTrainingRoute
  '/campaigns/$id': typeof AppCampaignsIdRoute
  '/campaigns/new': typeof AppCampaignsNewRoute
  '/customers/$id': typeof AppCustomersIdRoute
  '/segments/$slug': typeof AppSegmentsSlugRoute
  '/voice/$callId': typeof AppVoiceCallIdRoute
  '/agents/': typeof AppAgentsIndexRoute
  '/analytics/': typeof AppAnalyticsIndexRoute
  '/appointments/': typeof AppAppointmentsIndexRoute
  '/campaigns/': typeof AppCampaignsIndexRoute
  '/customers/': typeof AppCustomersIndexRoute
  '/integrations/': typeof AppIntegrationsIndexRoute
  '/journey/': typeof AppJourneyIndexRoute
  '/segments/': typeof AppSegmentsIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/users/': typeof AppUsersIndexRoute
  '/voice/': typeof AppVoiceIndexRoute
  '/whatsapp/': typeof AppWhatsappIndexRoute
  '/agents/recordings/review': typeof AppAgentsRecordingsReviewRoute
  '/agents/recordings/': typeof AppAgentsRecordingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/api/tts': typeof ApiTtsRoute
  '/agents/$agentId': typeof AppAgentsAgentIdRoute
  '/agents/training': typeof AppAgentsTrainingRoute
  '/campaigns/$id': typeof AppCampaignsIdRoute
  '/campaigns/new': typeof AppCampaignsNewRoute
  '/customers/$id': typeof AppCustomersIdRoute
  '/segments/$slug': typeof AppSegmentsSlugRoute
  '/voice/$callId': typeof AppVoiceCallIdRoute
  '/agents': typeof AppAgentsIndexRoute
  '/analytics': typeof AppAnalyticsIndexRoute
  '/appointments': typeof AppAppointmentsIndexRoute
  '/campaigns': typeof AppCampaignsIndexRoute
  '/customers': typeof AppCustomersIndexRoute
  '/integrations': typeof AppIntegrationsIndexRoute
  '/journey': typeof AppJourneyIndexRoute
  '/segments': typeof AppSegmentsIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/users': typeof AppUsersIndexRoute
  '/voice': typeof AppVoiceIndexRoute
  '/whatsapp': typeof AppWhatsappIndexRoute
  '/agents/recordings/review': typeof AppAgentsRecordingsReviewRoute
  '/agents/recordings': typeof AppAgentsRecordingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/api/tts': typeof ApiTtsRoute
  '/_app/agents/$agentId': typeof AppAgentsAgentIdRoute
  '/_app/agents/training': typeof AppAgentsTrainingRoute
  '/_app/campaigns/$id': typeof AppCampaignsIdRoute
  '/_app/campaigns/new': typeof AppCampaignsNewRoute
  '/_app/customers/$id': typeof AppCustomersIdRoute
  '/_app/segments/$slug': typeof AppSegmentsSlugRoute
  '/_app/voice/$callId': typeof AppVoiceCallIdRoute
  '/_app/agents/': typeof AppAgentsIndexRoute
  '/_app/analytics/': typeof AppAnalyticsIndexRoute
  '/_app/appointments/': typeof AppAppointmentsIndexRoute
  '/_app/campaigns/': typeof AppCampaignsIndexRoute
  '/_app/customers/': typeof AppCustomersIndexRoute
  '/_app/integrations/': typeof AppIntegrationsIndexRoute
  '/_app/journey/': typeof AppJourneyIndexRoute
  '/_app/segments/': typeof AppSegmentsIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/users/': typeof AppUsersIndexRoute
  '/_app/voice/': typeof AppVoiceIndexRoute
  '/_app/whatsapp/': typeof AppWhatsappIndexRoute
  '/_app/agents/recordings/review': typeof AppAgentsRecordingsReviewRoute
  '/_app/agents/recordings/': typeof AppAgentsRecordingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/api/tts'
    | '/agents/$agentId'
    | '/agents/training'
    | '/campaigns/$id'
    | '/campaigns/new'
    | '/customers/$id'
    | '/segments/$slug'
    | '/voice/$callId'
    | '/agents/'
    | '/analytics/'
    | '/appointments/'
    | '/campaigns/'
    | '/customers/'
    | '/integrations/'
    | '/journey/'
    | '/segments/'
    | '/settings/'
    | '/users/'
    | '/voice/'
    | '/whatsapp/'
    | '/agents/recordings/review'
    | '/agents/recordings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/api/tts'
    | '/agents/$agentId'
    | '/agents/training'
    | '/campaigns/$id'
    | '/campaigns/new'
    | '/customers/$id'
    | '/segments/$slug'
    | '/voice/$callId'
    | '/agents'
    | '/analytics'
    | '/appointments'
    | '/campaigns'
    | '/customers'
    | '/integrations'
    | '/journey'
    | '/segments'
    | '/settings'
    | '/users'
    | '/voice'
    | '/whatsapp'
    | '/agents/recordings/review'
    | '/agents/recordings'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/dashboard'
    | '/api/tts'
    | '/_app/agents/$agentId'
    | '/_app/agents/training'
    | '/_app/campaigns/$id'
    | '/_app/campaigns/new'
    | '/_app/customers/$id'
    | '/_app/segments/$slug'
    | '/_app/voice/$callId'
    | '/_app/agents/'
    | '/_app/analytics/'
    | '/_app/appointments/'
    | '/_app/campaigns/'
    | '/_app/customers/'
    | '/_app/integrations/'
    | '/_app/journey/'
    | '/_app/segments/'
    | '/_app/settings/'
    | '/_app/users/'
    | '/_app/voice/'
    | '/_app/whatsapp/'
    | '/_app/agents/recordings/review'
    | '/_app/agents/recordings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ApiTtsRoute: typeof ApiTtsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/tts': {
      id: '/api/tts'
      path: '/api/tts'
      fullPath: '/api/tts'
      preLoaderRoute: typeof ApiTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/agents/': {
      id: '/_app/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof AppAgentsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agents/$agentId': {
      id: '/_app/agents/$agentId'
      path: '/agents/$agentId'
      fullPath: '/agents/$agentId'
      preLoaderRoute: typeof AppAgentsAgentIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agents/training': {
      id: '/_app/agents/training'
      path: '/agents/training'
      fullPath: '/agents/training'
      preLoaderRoute: typeof AppAgentsTrainingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics/': {
      id: '/_app/analytics/'
      path: '/analytics'
      fullPath: '/analytics/'
      preLoaderRoute: typeof AppAnalyticsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/appointments/': {
      id: '/_app/appointments/'
      path: '/appointments'
      fullPath: '/appointments/'
      preLoaderRoute: typeof AppAppointmentsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/campaigns/': {
      id: '/_app/campaigns/'
      path: '/campaigns'
      fullPath: '/campaigns/'
      preLoaderRoute: typeof AppCampaignsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/campaigns/$id': {
      id: '/_app/campaigns/$id'
      path: '/campaigns/$id'
      fullPath: '/campaigns/$id'
      preLoaderRoute: typeof AppCampaignsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/campaigns/new': {
      id: '/_app/campaigns/new'
      path: '/campaigns/new'
      fullPath: '/campaigns/new'
      preLoaderRoute: typeof AppCampaignsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers/': {
      id: '/_app/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof AppCustomersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers/$id': {
      id: '/_app/customers/$id'
      path: '/customers/$id'
      fullPath: '/customers/$id'
      preLoaderRoute: typeof AppCustomersIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/integrations/': {
      id: '/_app/integrations/'
      path: '/integrations'
      fullPath: '/integrations/'
      preLoaderRoute: typeof AppIntegrationsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/journey/': {
      id: '/_app/journey/'
      path: '/journey'
      fullPath: '/journey/'
      preLoaderRoute: typeof AppJourneyIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/segments/': {
      id: '/_app/segments/'
      path: '/segments'
      fullPath: '/segments/'
      preLoaderRoute: typeof AppSegmentsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/segments/$slug': {
      id: '/_app/segments/$slug'
      path: '/segments/$slug'
      fullPath: '/segments/$slug'
      preLoaderRoute: typeof AppSegmentsSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users/': {
      id: '/_app/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AppUsersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/voice/': {
      id: '/_app/voice/'
      path: '/voice'
      fullPath: '/voice/'
      preLoaderRoute: typeof AppVoiceIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/voice/$callId': {
      id: '/_app/voice/$callId'
      path: '/voice/$callId'
      fullPath: '/voice/$callId'
      preLoaderRoute: typeof AppVoiceCallIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/whatsapp/': {
      id: '/_app/whatsapp/'
      path: '/whatsapp'
      fullPath: '/whatsapp/'
      preLoaderRoute: typeof AppWhatsappIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agents/recordings/': {
      id: '/_app/agents/recordings/'
      path: '/agents/recordings'
      fullPath: '/agents/recordings/'
      preLoaderRoute: typeof AppAgentsRecordingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agents/recordings/review': {
      id: '/_app/agents/recordings/review'
      path: '/agents/recordings/review'
      fullPath: '/agents/recordings/review'
      preLoaderRoute: typeof AppAgentsRecordingsReviewRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppAgentsAgentIdRoute: typeof AppAgentsAgentIdRoute
  AppAgentsTrainingRoute: typeof AppAgentsTrainingRoute
  AppCampaignsIdRoute: typeof AppCampaignsIdRoute
  AppCampaignsNewRoute: typeof AppCampaignsNewRoute
  AppCustomersIdRoute: typeof AppCustomersIdRoute
  AppSegmentsSlugRoute: typeof AppSegmentsSlugRoute
  AppVoiceCallIdRoute: typeof AppVoiceCallIdRoute
  AppAgentsIndexRoute: typeof AppAgentsIndexRoute
  AppAnalyticsIndexRoute: typeof AppAnalyticsIndexRoute
  AppAppointmentsIndexRoute: typeof AppAppointmentsIndexRoute
  AppCampaignsIndexRoute: typeof AppCampaignsIndexRoute
  AppCustomersIndexRoute: typeof AppCustomersIndexRoute
  AppIntegrationsIndexRoute: typeof AppIntegrationsIndexRoute
  AppJourneyIndexRoute: typeof AppJourneyIndexRoute
  AppSegmentsIndexRoute: typeof AppSegmentsIndexRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
  AppUsersIndexRoute: typeof AppUsersIndexRoute
  AppVoiceIndexRoute: typeof AppVoiceIndexRoute
  AppWhatsappIndexRoute: typeof AppWhatsappIndexRoute
  AppAgentsRecordingsReviewRoute: typeof AppAgentsRecordingsReviewRoute
  AppAgentsRecordingsIndexRoute: typeof AppAgentsRecordingsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppAgentsAgentIdRoute: AppAgentsAgentIdRoute,
  AppAgentsTrainingRoute: AppAgentsTrainingRoute,
  AppCampaignsIdRoute: AppCampaignsIdRoute,
  AppCampaignsNewRoute: AppCampaignsNewRoute,
  AppCustomersIdRoute: AppCustomersIdRoute,
  AppSegmentsSlugRoute: AppSegmentsSlugRoute,
  AppVoiceCallIdRoute: AppVoiceCallIdRoute,
  AppAgentsIndexRoute: AppAgentsIndexRoute,
  AppAnalyticsIndexRoute: AppAnalyticsIndexRoute,
  AppAppointmentsIndexRoute: AppAppointmentsIndexRoute,
  AppCampaignsIndexRoute: AppCampaignsIndexRoute,
  AppCustomersIndexRoute: AppCustomersIndexRoute,
  AppIntegrationsIndexRoute: AppIntegrationsIndexRoute,
  AppJourneyIndexRoute: AppJourneyIndexRoute,
  AppSegmentsIndexRoute: AppSegmentsIndexRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
  AppUsersIndexRoute: AppUsersIndexRoute,
  AppVoiceIndexRoute: AppVoiceIndexRoute,
  AppWhatsappIndexRoute: AppWhatsappIndexRoute,
  AppAgentsRecordingsReviewRoute: AppAgentsRecordingsReviewRoute,
  AppAgentsRecordingsIndexRoute: AppAgentsRecordingsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ApiTtsRoute: ApiTtsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
